import teachIcon from "../assets/images/teach.png";
export const courseData = [
	{
		id: "t1",
		ttl: "Getting Started",
		lects: "10",
		dur: "41min",
		list: [
			{
				id: "t11",
				ttl: "Async-Wait",
				dur: "01:04",
				preview: true,
				type: "video",
				link: "https://www.youtube.com/watch?v=bLre6Uf4Op0&pp=ygUWYXN5bmMgYXdhaXQgamF2YXNjcmlwdA%3D%3D",
				desc: "",
				resources: [
					{
						id: "t111",
						text: "css file",
						link: "https://github.com/",
						icon: teachIcon,
						downloadable: false,
					},
				],
			},
			{
				id: "t12",
				ttl: "JavaSCript Catch",
				dur: "01:04",
				preview: true,
				type: "video",
				link: "https://www.youtube.com/watch?v=WRNBQCl_cPU&pp=ygUIdHJ5Y2F0Y2g%3D",
				desc: "",
				resources: [
					{
						id: "t112",
						text: "css file",
						link: "https://github.com/",
						icon: teachIcon,
						downloadable: true,
					},
				],
			},
			{
				id: "t13",
				ttl: "Converting CallBack",
				dur: "01:04",
				preview: true,
				type: "video",
				link: "https://www.youtube.com/watch?v=btj35dh3_U8&pp=ygUIY2FsbGJhY2s%3D",
				desc: "",
				resources: [
					{
						id: "t113",
						text: "css file",
						link: "https://github.com/",
						icon: teachIcon,
						downloadable: false,
					},
					{
						id: "t114",
						text: "html file",
						link: "https://github.com/",
						icon: teachIcon,
						downloadable: false,
					},
				],
			},
			{
				id: "t14",
				ttl: "JavaScript CreateElement",
				dur: "01:04",
				preview: true,
				type: "video",
				link: "https://www.youtube.com/watch?v=VW8kNAous88&pp=ygUYY3JlYXRlZWxlbWVudCBqYXZhc2NyaXB0",
				desc: "This is a sample document description.",
			},
			{
				id: "t15",
				ttl: "Delete and HasOwnProperty",
				dur: "01:04",
				preview: false,
				type: "video",
				link: "https://www.youtube.com/watch?v=9EYx1OsP__g&pp=ygUOaGFzb3ducHJvcGVydHk%3D",
				desc: "This is a sample document description.",
			},
			{
				id: "t16",
				ttl: "DOM Manipulation",
				dur: "01:04",
				preview: true,
				type: "video",
				link: "https://www.youtube.com/watch?v=fYR3i0mcE5c&pp=ygUeZG9tIG1hbmlwdWxhdGlvbiBpbiBqYXZhc2NyaXB0",
				desc: "",
			},
			{
				id: "t17",
				ttl: "Error Handling",
				dur: "01:04",
				preview: false,
				type: "video",
				link: "https://www.youtube.com/watch?v=WRNBQCl_cPU&pp=ygUcZXJyb3IgaGFuZGxpbmcgaW4gamF2YXNjcmlwdA%3D%3D",
				desc: "",
			},
			{
				id: "t18",
				ttl: "Function Prototype",
				dur: "01:04",
				preview: false,
				type: "video",
				link: "https://www.youtube.com/watch?v=jxW7iwCtBZk&pp=ygUSZnVuY3Rpb24gcHJvdG90eXBl",
				desc: "This is a sample document description.",
			},
		],
	},
	{
		id: "t2",
		ttl: "Javascript Refresher",
		lects: "10",
		dur: "41min",
		list: [
			{
				id: "t21",
				ttl: "Intorduction - Part 1",
				dur: "01:04",
				preview: true,
				type: "video",
				link: "https://www.youtube.com/watch?v=wstwjQ1yqWQ&pp=ygUSZnVuY3Rpb24gcHJvdG90eXBl",
				desc: "",
			},
			{
				id: "t22",
				ttl: "Introduction Part-2",
				dur: "01:04",
				preview: true,
				type: "video",
				link: "https://www.youtube.com/watch?v=lML4vruKl0Q&pp=ygUSZnVuY3Rpb24gcHJvdG90eXBl",
				desc: "",
			},
			{
				id: "t23",
				ttl: "Nesting Catch",
				dur: "01:04",
				preview: true,
				type: "video",
				link: "https://www.youtube.com/watch?v=yfYY4ykJgK8&pp=ygUSZnVuY3Rpb24gcHJvdG90eXBl",
				desc: "",
			},
		],
	},
];
